services:
  desktop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    restart: unless-stopped
    shm_size: "1gb"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: America/New_York
      TITLE: Brian's Cloud Desktop
      PIXELFLUX_WAYLAND: "false"
      SELKIES_USE_CPU: "true|locked"
      SELKIES_ENCODER: "jpeg"
      SELKIES_FRAMERATE: "8-30"
      SELKIES_AUDIO_ENABLED: "true"
      SELKIES_MICROPHONE_ENABLED: "false|locked"
      SELKIES_ENABLE_SHARING: "false|locked"
      SELKIES_ENABLE_COLLAB: "false|locked"
      SELKIES_ENABLE_SHARED: "false|locked"
      START_DOCKER: "false"
    volumes:
      - ..:/workspaces/my-cloud-desktop:cached
      - desktop-home:/config

volumes:
  desktop-home:
